### ISSUE TITLE
issue with web3modal contructor

### ISSUE THREAD

**Issue by ShravanSunder** [scaffold-eth/scaffold-eth-typescript#77]
```
Uhoh! There was an error!
TypeError: import_web3modal.default is not a constructor
    at EthersModalConnector.loadCore (http://localhost:3000/node_modules/.vite/chunk-LNEPW6E3.js?v=08d3923f:314:43)
    at autoConnectToBurner (http://localhost:3000/src/components/main/hooks/useScaffoldAppProviders.ts:44:19)
    at http://localhost:3000/src/components/main/hooks/useScaffoldAppProviders.ts:59:19
    at invokePassiveEffectCre

...

/.vite/chunk-RJUD5BXP.js?v=08d3923f:3671:22)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/node_modules/.vite/chunk-RJUD5BXP.js?v=08d3923f:3696:24)
    at invokeGuardedCallback (http://localhost:3000/node_modules/.vite/chunk-RJUD5BXP.js?v=08d3923f:3730:39)
    at flushPassiveEffectsImpl (http://localhost:3000/node_modules/.vite/chunk-RJUD5BXP.js?v=08d3923f:16819:17)
    at unstable_runWithPriority (http://localhost:3000/node_modules/.vite/chunk-RJUD5BXP.js?v=08d3923f:346:20)
    at runWithPriority$1 (http://localhost:3000/node_modules/.vite/chunk-RJUD5BXP.js?v=08d3923f:8468:18)
```

**Comment by grothem** [comment]
I'm seeing bug with the provider modal, I'm not sure if it's related to this issue or not. When I change the target network env variable from local host a test network, the provider modal won't open when I restart the app. I just get a spinner on the connect button, but the modal never opens.

If I open an incognito tab, or clear local storage, then the modal does show when I try to connect.

**Comment by georgeportillo** [comment]
Also encountering this issue.
